### ISSUE TITLE
When I run Train, I get this error "AttributeError: 'NoneType' object has no attribute 'message_types_by_name'"

### ISSUE THREAD

**Issue by juandavidGF** [JoePenna/Dreambooth-Stable-Diffusion#105]
When I run Train, I get this error "AttributeError: 'NoneType' object has no attribute 'message_types_by_name'"

When I install the dependencies (Build Env), in some point I get
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.

So I updated protobuf to version 3.12.2, 3.9.2. And apparently, the error message disappears. 

But when I try to start the train, I get:
Traceback (most recent call last):
  File "/workspace/Dreambooth-Stable-Diffusion/main.py", line 2, in <module>
    from ldm.modules.pruningckptio import PruningCheckpointIO
  File "/workspace/Dreambooth-Stable-Diffusion/ldm/modules/pruningckptio.py", line 1, in <module>
    from pytorch_lightning.plugins.io.torch_plugin import TorchCheckpointIO
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/imports.py", line 121, in <module>
    _WANDB_GREATER_EQUAL_0_10_22 = _WANDB_AVAILABLE and _compare_version("wandb", operator.ge, "0.10.22")
  File "/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/imports.py", line 71, in _compare_version
    pkg = importlib.import_module(package)
  File "/venv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/venv/lib/python3.10/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/venv/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "/venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "/venv/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "/venv/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "/venv/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "/venv/lib/python3.10/site-packages/wandb/sdk/lib/proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/venv/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "/venv/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/venv/lib/python3.10/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "/venv/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

I searched this error, and I found: https://github.com/protocolbuffers/protobuf/issues/10075.

So I have tried to install another protobuf versions, but nothing have worked.

**Comment by juandavidGF** [comment]
ok, I run again today, and apparently It works 🤔
