### ISSUE TITLE
Error during training - Invalid load key

### ISSUE THREAD

**Issue by Erpix3lt** [JoePenna/Dreambooth-Stable-Diffusion#108]
Hi there I have done everything according to Aitrepreneurs [video](https://www.youtube.com/watch?v=7m__xadX0z0)
Somehow training fails. I have already fixed the Trainer bug, changing the first letter to upper case. 
After some research I was not able to find something similar to the error below. Help is much appreciated!

```
Global seed set to 23
Running on GPUs 0,
Loading model from model.ckpt
Traceback (most recent call last):
  File "/home/jovyan/Dreambooth-Stable-Diffusion/main.py", line 683, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "/home/jovyan/Dreambooth-Stable-Diffusion/main.py", line 30, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by Erpix3lt** [comment]
i think i can Close this one
