### ISSUE TITLE
model 2.1

### ISSUE THREAD

**Issue by OoAnikioO** [JoePenna/Dreambooth-Stable-Diffusion#137]
### Discussed in https://github.com/JoePenna/Dreambooth-Stable-Diffusion/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **OoAnikioO** December 25, 2022</sup>
Does the notebook work with the model 2.1 with 768 images?
I tried to upload v2-1_768-nonema-pruned.ckpt rename to model with the yaml file and run a training but I got only errors

Global seed set to 23
Running on GPUs 0,
Loading model from model.ckpt
Traceback (most recent call last):
  File "/workspace/Dreambooth-Stable-Diffusion/main.py", line 683, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "/workspace/Dreambooth-Stable-Diffusion/main.py", line 33, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/workspace/Dreambooth-Stable-Diffusion/ldm/util.py", line 87, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/workspace/Dreambooth-Stable-Diffusion/ldm/util.py", line 95, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspace/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 26, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/workspace/Dreambooth-Stable-Diffusion/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Dreambooth-Stable-Diffusion/main.py", line 896, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined</div>

**Comment by juandavidGF** [comment]
I got the same error with proton model, were you able to you fix it?

**Comment by OoAnikioO** [comment]
no, and i have like you the error with protogen
you have tested other models ?   realisticVision, dreamlike, .....
