### ISSUE TITLE
pickle.UnpicklingError: invalid load key - Issue Using Safetensor training model

### ISSUE THREAD

**Issue by Acephalia** [JoePenna/Dreambooth-Stable-Diffusion#196]
Hello thank you for all the great work on this. I am just trying this version after I've upgraded to a capable graphic card. Windows install using the recommended guide and I've successfully run a training with a ckpt model. I was trying to use a safetensors version of another model and the following error popped up. Hoping someone maybe able to assist to rectify. 

```
Traceback (most recent call last):
  File "R:\Dreambooth-Stable-Diffusion\main.py", line 159, in <module>
    model = load_model_from_config(
  File "R:\Dreambooth-Stable-Diffusion\ldm\util.py", line 79, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "S:\Miniconda\envs\dreambooth_joepenna\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "S:\Miniconda\envs\dreambooth_joepenna\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '&'.
```

Thank you

**Comment by Acephalia** [comment]
Fixed by converting model to ckpt using [convert tool](https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI)
