### ISSUE TITLE
Torch Install Failure: "raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by potesd** [JoePenna/Dreambooth-Stable-Diffusion#199]
After following the install guide to the letter, torch failed to compile with CUDA enabled. 

```
Traceback (most recent call last):
  File "C:\Users\ShiftSpace\Dreambooth-Stable-Diffusion\main.py", line 138, in <module>
    dreambooth_config: JoePennaDreamboothConfigSchemaV1 = parse_arguments()
  File "C:\Users\ShiftSpace\Dreambooth-Stable-Diffusion\dreambooth_helpers\arguments.py", line 145, in parse_arguments
    config.saturate(
  File "C:\Users\ShiftSpace\Dreambooth-Stable-Diffusion\dreambooth_helpers\joepenna_dreambooth_config.py", line 143, in saturate
    self.validate_gpu_vram()
  File "C:\Users\ShiftSpace\Dreambooth-Stable-Diffusion\dreambooth_helpers\joepenna_dreambooth_config.py", line 159, in validate_gpu_vram
    gpu_vram = int(torch.cuda.get_device_properties(self.gpu).total_memory)
  File "C:\Users\ShiftSpace\.conda\envs\dreambooth_joepenna\lib\site-packages\torch\cuda\__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\Users\ShiftSpace\.conda\envs\dreambooth_joepenna\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by yushan777** [comment]
This guide?

https://medium.com/@yushantripleseven/dreambooth-training-joepenna-on-a-local-pc-windows-f00a4fd11dfd?sk=0364c123bb39ffb1c4ea897615403aab
