### ISSUE TITLE
Runtime Error: Regularization Images - # GENERATE 200 images - Optional

### ISSUE THREAD

**Issue by vlsech** [JoePenna/Dreambooth-Stable-Diffusion#61]
Hello Joe

Great work. I had run this many time previously; however, recently this section errors out out the end.

Here are there errors displayed:

DIM Sampler: 100%|█████████████████████████████| 50/50 [00:05<00:00,  8.36it/s]

data: 100%|███████████████████████████████████████| 1/1 [00:06<00:00,  6.13s/it]
Sampling: 100%|███████████████████████████████| 200/200 [20:32<00:00,  6.16s/it]
Maximum supported image dimension is 65500 pixels
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 292, in <module>
    main()
  File "scripts/stable_txt2img.py", line 280, in main
    Image.fromarray(grid.astype(np.uint8)).save(os.path.join(outpath, f'{prompt.replace(" ", "-")}-{grid_count:04}.jpg'))
  File "/venv/lib/python3.8/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/venv/lib/python3.8/site-packages/PIL/JpegImagePlugin.py", line 783, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFile.py", line 529, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file

Thanks,

Vince

P.S. I have found it is better to run my own 200 images as facial features like nose shapes are better using it.

**Comment by JBlakeMCAA** [comment]
Having the same issue
Maximum supported image dimension is 65500 pixels
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 292, in <module>
    main()
  File "scripts/stable_txt2img.py", line 280, in main
    Image.fromarray(grid.astype(np.uint8)).save(os.path.join(outpath, f'{prompt.replace(" ", "-")}-{grid_count:04}.jpg'))
  File "/venv/lib/python3.8/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/venv/lib/python3.8/site-packages/PIL/JpegImagePlugin.py", line 783, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFile.py", line 529, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file

**Comment by JBlakeMCAA** [comment]
How can you run your own 200 images?

**Comment by SWivid** [comment]
I think this error doesn't matter. In fact 200 figures were just rightly output in your assigned folder without a long scoll-down overview of all-200-in-one figure.
If you try with just 10 output, you will have that all-10-in-one overview fig.
