### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by ExiaCyn** [JoePenna/Dreambooth-Stable-Diffusion#96]
I've been trying to run the repo on a locally installed copy of Jupyter Labs using Ubuntu 22. I've managed to solve nearly all the issues but hit this one and I can't solve it. Anyone else encountered this with a fix whilst running ubuntu on a windows PC?

Traceback (most recent call last):
  File "/home/cyndre/Dreambooth-Stable-Diffusion/main.py", line 875, in <module>
    trainer.fit(model, data)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/cyndre/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/cyndre/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 368, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "/home/cyndre/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 908, in shared_step
    loss = self(x, c)
  File "/home/cyndre/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cyndre/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 945, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/home/cyndre/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 1096, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by ExiaCyn** [comment]
After some trial and error from another linked issue I managed to nix this error but immediately got a new one;

RuntimeError: No CUDA GPUs are available

I'm using an RTX 3090 Strix

**Comment by chakalakasp** [comment]
If using vast.ai, use an older version of CUDA to use -- the "latest" build breaks this script.  The 1.12.1 version seems to work fine

**Comment by djbielejeski** [comment]
@chakalakasp do you have steps to fix this so we can update the script?

**Comment by chakalakasp** [comment]
Hi - unfortunately no, I didn’t dig into the script to figure out the issue, which I suspect is some sort of incompatibility with a recent update to the CUDA environment used with PyTorch by vast.ai (and probably others, if they stay updated). I simply used the previous version of PyTorch. This was something I selected at vast.ai before I even launched the machine.

**Comment by djbielejeski** [comment]
Select 1.12.1 as your version of PyTorch in the configs, should fix this.

![image](https://user-images.githubusercontent.com/2463282/198888938-b91a3c4a-2ca3-43e5-b220-a993212d7e56.png)

**Comment by askerlee** [comment]
@chakalakasp Thanks. I'm using pip, and downgrading to torch 1.12 fixes the problem:
`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113`

**Comment by vshulman** [comment]
a simpler solution that allows you to keep the latest version of torch is to patch `ddpm.py` on L1096 with `logvar_t = self.logvar[t.cpu()].to(self.device)`, i.e. add `.cpu()` to the step counter

**Comment by degusssa** [comment]
> a simpler solution that allows you to keep the latest version of torch is to patch `ddpm.py` on L1096 with `logvar_t = self.logvar[t.cpu()].to(self.device)`, i.e. add `.cpu()` to the step counter

Maybe create a PR for this, if it works with all versions? @vshulman

**Comment by strangerstork** [comment]
> > a simpler solution that allows you to keep the latest version of torch is to patch `ddpm.py` on L1096 with `logvar_t = self.logvar[t.cpu()].to(self.device)`, i.e. add `.cpu()` to the step counter
> 
> Maybe create a PR for this, if it works with all versions? @vshulman

totally fair. I've not had a chance to test it with other versions of torch, but should I get around to it, I'll PR.

**Comment by vshulman** [comment]
> > a simpler solution that allows you to keep the latest version of torch is to patch `ddpm.py` on L1096 with `logvar_t = self.logvar[t.cpu()].to(self.device)`, i.e. add `.cpu()` to the step counter
> 
> Maybe create a PR for this, if it works with all versions? @vshulman

totally fair. I've not had a chance to test it with other versions of torch, but should I get around to it, I'll PR.
